/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("spdx.repro.kotlin-application-conventions")
    id("org.spdx.sbom") version "0.6.0"
    id("org.jetbrains.kotlin.plugin.spring") version "1.9.10" apply false
    id("org.springframework.boot") version "3.1.9" apply false
}

dependencies {
    api(platform("org.springframework.boot:spring-boot-dependencies:3.1.9"))
    api(platform("org.springframework.cloud:spring-cloud-dependencies:2022.0.4"))
    implementation("org.apache.commons:commons-text")
    implementation(project(":utilities"))
    implementation(group = "io.netty", name = "netty-resolver-dns-native-macos", classifier = "osx-aarch_64")
    implementation(group = "io.netty", name = "netty-resolver-dns-native-macos", classifier = "osx-x86_64")
}

application {
    // Define the main class for the application.
    mainClass.set("spdx.repro.app.AppKt")
}

spdxSbom {
    targets {
        // create a target named "release",
        // this is used for the task name (spdxSbomForRelease)
        // and output file (release.spdx.json)
        create("release") {
            // configure here
            configurations.set(listOf(project.configurations.runtimeClasspath.name))
        }
    }
}